# =========================================
# AESLATEK DEVICE AUDIT
# Hardware + Windows + Crack Detection
# =========================================

# Bắt buộc sử dụng TLS 1.2 để tránh lỗi SSL/TLS trên Windows đời cũ
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Clear-Host
$serverUrl = "https://scabby-blurb-unscathed.ngrok-free.dev/api/audit"

function Good($msg) { Write-Host "[ OK ] $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Bad($msg) { Write-Host "[BAD ] $msg" -ForegroundColor Red }

Write-Host "===== AESLATEK DEVICE AUDIT =====" -ForegroundColor Cyan

# OS
$osCaption = "Unknown OS (WMI Error)"
try {
    $OS = Get-CimInstance Win32_OperatingSystem -ErrorAction Stop
    if ($OS) { $osCaption = $OS.Caption }
} catch {}

# CPU
$CPUName = "Unknown CPU (WMI Error)"
$Cores = 0
$Threads = 0
$Clock = 0
try {
    $CPU = Get-CimInstance Win32_Processor -ErrorAction Stop
    if ($CPU) {
        $CPUName = $CPU.Name.Trim()
        $Cores = $CPU.NumberOfCores
        $Threads = $CPU.NumberOfLogicalProcessors
        $Clock = $CPU.MaxClockSpeed
    }
} catch {}

# RAM
$RAMGB = 0
try {
    $RAM = Get-CimInstance Win32_ComputerSystem -ErrorAction Stop
    if ($RAM) { $RAMGB = [math]::Round($RAM.TotalPhysicalMemory / 1GB) }
} catch {}

# RAM TYPE
$RamGeneration = "Unknown"
try {
    $RamModules = Get-CimInstance Win32_PhysicalMemory -ErrorAction Stop
    $RamTypes = @()
    if ($RamModules) {
        foreach ($r in $RamModules) {
            $Type = switch ($r.SMBIOSMemoryType) {
                20 { "DDR" }
                21 { "DDR2" }
                24 { "DDR3" }
                26 { "DDR4" }
                34 { "DDR5" }
                default { "Unknown" }
            }
            $RamTypes += $Type
        }
        $RamGeneration = ($RamTypes | Select-Object -Unique) -join ", "
    }
} catch {}

# MAINBOARD
$Mainboard = "Unknown Board"
try {
    $Board = Get-CimInstance Win32_BaseBoard -ErrorAction Stop
    if ($Board) { $Mainboard = "$($Board.Manufacturer) $($Board.Product)".Trim() }
} catch {}

# STORAGE
$DiskType = "Unknown"
$DiskName = "Unknown"
$diskFree = 0
try {
    $cDrive = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" -ErrorAction Stop
    if ($cDrive) { $diskFree = [math]::Round($cDrive.FreeSpace / 1GB, 2) }
    
    $Disks = Get-PhysicalDisk -ErrorAction SilentlyContinue
    $DiskArray = @()
    if ($Disks) {
        foreach ($d in $Disks) {
            $sizeGB = [math]::Round($d.Size / 1GB)
            $type = $d.MediaType
            if ([string]::IsNullOrWhiteSpace($type) -or $type -eq "Unspecified") { $type = "Unknown" }
            $DiskArray += "$type ($sizeGB GB)"
            if ($d.DeviceId -eq (Get-Partition -DriveLetter C).DiskNumber) {
                $DiskType = $type
                $DiskName = $d.FriendlyName
            }
        }
    }
    $StorageConfig = $DiskArray -join " + "
    if (-not $StorageConfig) { $StorageConfig = "C: ($diskFree GB Free)" }
} catch { $StorageConfig = "Unknown" }

# TPM
$TPMEnabled = "No (No Admin)"
try {
    $isAdmin = (New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if ($isAdmin) {
        $TPM = Get-Tpm -ErrorAction Stop
        if ($TPM.TpmPresent) { $TPMEnabled = "Yes" } else { $TPMEnabled = "No" }
    }
} catch { $TPMEnabled = "Unknown" }

# WINDOWS LICENSE
$LicenseChannel = "Unknown"
try {
    $License = Get-CimInstance SoftwareLicensingProduct -ErrorAction Stop | Where-Object { $_.PartialProductKey -and $_.Name -match "Windows" } | Select-Object -First 1
    if ($License) {
        if ($License.Description -match "RETAIL") { $LicenseChannel = "Retail" }
        elseif ($License.Description -match "OEM") { $LicenseChannel = "OEM" }
        elseif ($License.Description -match "KMS") { $LicenseChannel = "KMS" }
        elseif ($License.Description -match "MAK") { $LicenseChannel = "MAK" }
    }
} catch {}

# CRACK DETECTION
$CrackDetected = $false
$CrackReason = ""

# Check MAS (Microsoft Activation Scripts) HWID Digital License
$masReg = reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform" /v KeyManagementServiceName 2>$null
if ($masReg) { $CrackDetected = $true; $CrackReason = "KMS Server (MAS/Pico)" }

# Check for HWID/KMS38 specific tasks (MAS v2.0+)
$tasks = Get-ScheduledTask -ErrorAction SilentlyContinue | Where-Object { $_.TaskName -match "KMS|MAS|AutoPico|Activator|HWID|SppExtComObjHook" }
if ($tasks) { $CrackDetected = $true; $CrackReason += " | Suspicious Task" }

# Check for specific files generated by MAS
if (Test-Path "C:\Windows\System32\SppExtComObjHook.dll") { $CrackDetected = $true; $CrackReason += " | KMS Hook DLL" }
if (Test-Path "C:\Windows\System32\AAct_x64.exe") { $CrackDetected = $true; $CrackReason += " | AAct Activator" }
if (Test-Path "C:\Windows\System32\KMS-R@1n.exe") { $CrackDetected = $true; $CrackReason += " | KMS-R@1n" }

$services = Get-Service -ErrorAction SilentlyContinue | Where-Object { $_.Name -match "KMS|Pico|Activator" }
if ($services) { $CrackDetected = $true; $CrackReason += " | Suspicious Service" }

if ($LicenseChannel -eq "KMS") { $CrackDetected = $true; $CrackReason += " | Volume KMS Activation" }

# OFFICE VERSION & CRACK
$OfficeVersion = "Not Installed"
$OfficeCrack = "Clean"

$ctrReg = "HKLM:\SOFTWARE\Microsoft\Office\ClickToRun\Configuration"
if (Test-Path $ctrReg) {
    $products = (Get-ItemProperty $ctrReg -Name "ProductReleaseIds" -ErrorAction SilentlyContinue).ProductReleaseIds
    if ($products) { $OfficeVersion = $products }
}
if ($OfficeVersion -eq "Not Installed") {
    if (Test-Path "HKLM:\SOFTWARE\Microsoft\Office\16.0\Common\ProductVersion") {
        $OfficeVersion = "Office 2016/2019/2021 (MSI)"
    }
}

# Check MAS Ohook DLL
if (Test-Path "C:\Program Files\Microsoft Office\root\vfs\System\sppc.dll") { $OfficeCrack = "Ohook (MAS)" }
if (Test-Path "C:\Program Files (x86)\Microsoft Office\root\vfs\System\sppc.dll") { $OfficeCrack = "Ohook (MAS)" }

# Check KMS Office via OSPP
$osppPath = ""
if (Test-Path "C:\Program Files\Microsoft Office\Office16\ospp.vbs") { $osppPath = "C:\Program Files\Microsoft Office\Office16\ospp.vbs" }
elseif (Test-Path "C:\Program Files (x86)\Microsoft Office\Office16\ospp.vbs") { $osppPath = "C:\Program Files (x86)\Microsoft Office\Office16\ospp.vbs" }

if ($osppPath) {
    $osppOut = cscript //nologo $osppPath /dstatus
    if ($osppOut -match "VOLUME_KMSCLIENT" -and $osppOut -match "LICENSED") {
        $OfficeCrack = "KMS Server"
    }
}

if ($OfficeCrack -ne "Clean") {
    $CrackDetected = $true
    $CrackReason += " | Office Crack ($OfficeCrack)"
}
$CrackReason = $CrackReason.Trim(" | ")

# WINDOWS 11 COMPATIBILITY CHECK
$Win11CPU = $false
if ($CPUName -match "i[3579]-(\d{4,5})") {
    $genStr = $matches[1]
    if ($genStr.Length -eq 4 -and [int]$genStr.Substring(0,1) -ge 8) { $Win11CPU = $true }
    elseif ($genStr.Length -eq 5) { $Win11CPU = $true }
} elseif ($CPUName -match "Ryzen \d (\d)\d{3}") {
    if ([int]$matches[1] -ge 2) { $Win11CPU = $true }
} elseif ($CPUName -match "Core Ultra") {
    $Win11CPU = $true
}

# SCORING
$Score = 0

# Cores penalty
if ([int]$Cores -ge 8) { $Score += 4 }
elseif ([int]$Cores -ge 6) { $Score += 3 }
elseif ([int]$Cores -ge 4) { $Score += 2 }

# RAM
if ([int]$RAMGB -ge 16) { $Score += 4 }
elseif ([int]$RAMGB -ge 8) { $Score += 2 }

# SSD
if ($DiskType -eq "SSD") { $Score += 2 }

# Win11 CPU Bonus
if ($Win11CPU) { $Score += 2 }

# MACHINE TIER
$Tier = ""
$WindowsPlan = ""
$M365Plan = ""

if ($Score -ge 9) {
    $Tier = "HIGH END"
    $M365Plan = "M365 Business Premium"
} elseif ($Score -ge 5) {
    $Tier = "MID RANGE"
    $M365Plan = "M365 Business Standard"
} else {
    $Tier = "LOW END"
    $M365Plan = "Office Web / LTSC"
}

# Strict Windows Plan (Requires Win11 CPU + 8GB RAM + SSD)
if ($Win11CPU -and [int]$RAMGB -ge 8 -and $DiskType -eq "SSD") {
    $WindowsPlan = "Windows 11 Pro / Ent"
} else {
    $WindowsPlan = "Windows 10 Pro"
}

# NETWORK
$netAdapter = Get-NetAdapter | Where-Object Status -eq 'Up' | Select-Object -First 1
$ipObj = Get-NetIPAddress -InterfaceIndex $netAdapter.ifIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue | Select-Object -First 1
$ip = if ($ipObj) { $ipObj.IPAddress } else { "Unknown" }
$mac = if ($netAdapter) { $netAdapter.MacAddress } else { "Unknown" }

# Lấy Key Windows
$key = "Not Found"
try {
    $svc = Get-WmiObject -query 'select * from SoftwareLicensingService' -ErrorAction Stop
    if ($svc) { $key = $svc.OA3xOriginalProductKey }
} catch {}
if ([string]::IsNullOrWhiteSpace($key) -or $key -eq "Not Found") {
    try { $key = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform" -ErrorAction Stop).BackupProductKeyDefault } catch {}
}
if ([string]::IsNullOrWhiteSpace($key)) { $key = "Not Found" }

$FinalHostname = $env:COMPUTERNAME
if ($UserPC) {
    $FinalHostname = "$UserPC ($env:COMPUTERNAME)"
}

$payload = @{
    machineId = $env:COMPUTERNAME
    hostname = $FinalHostname
    mainboard = $Mainboard
    osVersion = $osCaption
    cpu = "$CPUName ($Cores Cores / $Threads Threads)"
    ram = "$RAMGB GB $RamGeneration"
    disk = "Drive C: $DiskName | $StorageConfig"
    storageConfig = $StorageConfig
    ipAddress = $ip
    macAddress = $mac
    licenseKey = $key
    licenseStatus = $LicenseChannel
    officeVersion = $OfficeVersion
    officeCrack = $OfficeCrack
    tpmEnabled = $TPMEnabled
    crackDetected = $CrackDetected
    crackReason = $CrackReason
    score = $Score
    tier = $Tier
    windowsPlan = $WindowsPlan
    m365Plan = $M365Plan
}

if ($CrackDetected) { Bad "CRACK DETECTED ($CrackReason)" } else { Good "NO CRACK DETECTED" }

Write-Host "Đang gửi dữ liệu lên server: $serverUrl"
try {
    $response = Invoke-RestMethod -Uri $serverUrl -Method Post -Body ($payload | ConvertTo-Json) -ContentType "application/json" -Headers @{"ngrok-skip-browser-warning"="1"}
    if ($response.success) {
        Good "Gửi thông tin Audit thành công!"
    } else {
        Bad "Lỗi từ server: $($response.error)"
    }
} catch {
    Bad "Không thể kết nối tới server. Lỗi: $_"
}
